// angular-crud/src/app/components/create-rows/create-rows.component.ts
import { Component } from '@angular/core';
import { faker } from '@faker-js/faker';

@Component({
  selector: 'app-create-rows',
  standalone: true,
  templateUrl: './create-rows.component.html',
})
export class CreateRowsComponent {
  data: any[] = [];
  creationTime: number | null = null;

  createRows() {
    const startTime = performance.now();
    this.data = Array.from({ length: 10000 }, (_, i) => ({
      id: i + 1,
      name: faker.person.fullName(),
      email: faker.internet.email(),
      address: faker.location.streetAddress(),
    }));
    const endTime = performance.now();
    this.creationTime = endTime - startTime;
  }
}

<div>
  <h2>Criação de Linhas</h2>
  <button (click)="createRows()">Criar 10.000 Linhas</button>

  @if (creationTime) {
    <p>Tempo de criação: {{ creationTime }} ms</p>
  }

  @if (data.length) {
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Email</th>
          <th>Endereço</th>
        </tr>
      </thead>
      <tbody>
        @for (row of data; track row.id) {
          <tr>
            <td>{{ row.id }}</td>
            <td>{{ row.name }}</td>
            <td>{{ row.email }}</td>
            <td>{{ row.address }}</td>
          </tr>
        }
      </tbody>
    </table>
  }
</div>

// react-crud/src/components/createRows.js
"use client";

import { useState } from "react";
import { faker } from "@faker-js/faker";

const CreateRows = () => {
  const [data, setData] = useState([]);
  const [creationTime, setCreationTime] = useState(null);

  // Função para criar 10.000 novas linhas
  const createRows = () => {
    const startTime = performance.now();

    const newData = [];
    for (let i = 0; i < 10000; i++) {
      newData.push({
        id: i + 1,
        name: faker.person.fullName(),
        email: faker.internet.email(),
        address: faker.location.streetAddress(),
      });
    }

    setData(newData);

    const endTime = performance.now();
    setCreationTime(endTime - startTime);
  };

  return (
    <div>
      <h3>Criação de 10.000 novas linhas</h3>
      {creationTime && <p>Tempo de criação: {creationTime} ms</p>}
      <button onClick={createRows}>Criar 10.000 Linhas</button>

      {data.length > 0 && (
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Endereço</th>
            </tr>
          </thead>
          <tbody>
            {data.map((row) => (
              <tr key={row.id}>
                <td>{row.id}</td>
                <td>{row.name}</td>
                <td>{row.email}</td>
                <td>{row.address}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default CreateRows;
